steps:
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        terraform init
    id: terraform init 
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan 
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        terraform apply --auto-approve
    id: terraform apply --auto-approve
    entrypoint: sh
options:
  logging: CLOUD_LOGGING_ONLY
